services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    environment:
      - DO_AUTH_TOKEN=${DO_AUTH_TOKEN}
    configs:
      - source: traefik_static
        target: /traefik.yml
      - source: traefik_dynamic
        target: /config.yml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-acme:/letsencrypt
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.traefik.loadbalancer.server.port=8080'
      - 'traefik.http.routers.traefik.entrypoints=http'
      - 'traefik.http.routers.traefik.rule=Host(`traefik.console.lol`)'
      - 'traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$8EVjn/nj$$GiLUZqcbueTFeD23SuB6x0'
      - 'traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https'
      - 'traefik.http.routers.traefik.middlewares=traefik-https-redirect'
      - 'traefik.http.routers.traefik-secure.entrypoints=https'
      - 'traefik.http.routers.traefik-secure.rule=Host(`traefik.console.lol`)'
      - 'traefik.http.routers.traefik-secure.middlewares=traefik-auth'
      - 'traefik.http.routers.traefik-secure.tls=true'
      - 'traefik.http.routers.traefik-secure.tls.certresolver=digitalocean'
      - 'traefik.http.routers.traefik-secure.tls.domains[0].main=console.lol'
      - 'traefik.http.routers.traefik-secure.tls.domains[0].sans=*.console.lol'
      - 'traefik.http.routers.traefik-secure.service=api@internal'

volumes:
  traefik-acme:

configs:
  traefik_static:
    file: ./traefik/traefik.yml
  traefik_dynamic:
    file: ./traefik/config.yml
